/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanKu;

/**
 *
 * @author ASUS
 */
public class KendaraanMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form KendaraanMainFrame
     */
    public KendaraanMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonMotor = new javax.swing.JButton();
        buttonTruk = new javax.swing.JButton();
        buttonKeretaApi = new javax.swing.JButton();
        buttonSepeda3 = new javax.swing.JButton();
        buttonBus = new javax.swing.JButton();
        buttonKapal = new javax.swing.JButton();
        buttonPesawat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DATA INPUT KENDARAAN");

        buttonMotor.setBackground(new java.awt.Color(0, 102, 0));
        buttonMotor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonMotor.setForeground(new java.awt.Color(255, 255, 255));
        buttonMotor.setText("INPUT KENDARAAN MOTOR");
        buttonMotor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMotorActionPerformed(evt);
            }
        });

        buttonTruk.setBackground(new java.awt.Color(0, 102, 0));
        buttonTruk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTruk.setForeground(new java.awt.Color(255, 255, 255));
        buttonTruk.setText("INPUT KENDARAAN TRUK");
        buttonTruk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonTruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrukActionPerformed(evt);
            }
        });

        buttonKeretaApi.setBackground(new java.awt.Color(0, 102, 0));
        buttonKeretaApi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonKeretaApi.setForeground(new java.awt.Color(255, 255, 255));
        buttonKeretaApi.setText("INPUT KENDARAAN KERETA API");
        buttonKeretaApi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonKeretaApi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeretaApiActionPerformed(evt);
            }
        });

        buttonSepeda3.setBackground(new java.awt.Color(0, 102, 0));
        buttonSepeda3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSepeda3.setForeground(new java.awt.Color(255, 255, 255));
        buttonSepeda3.setText("INPUT KENDARAAN SEPEDA");
        buttonSepeda3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonSepeda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSepeda3ActionPerformed(evt);
            }
        });

        buttonBus.setBackground(new java.awt.Color(0, 102, 0));
        buttonBus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBus.setForeground(new java.awt.Color(255, 255, 255));
        buttonBus.setText("INPUT KENDARAAN BUS");
        buttonBus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBusActionPerformed(evt);
            }
        });

        buttonKapal.setBackground(new java.awt.Color(0, 102, 0));
        buttonKapal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonKapal.setForeground(new java.awt.Color(255, 255, 255));
        buttonKapal.setText("INPUT KENDARAAN KAPAL");
        buttonKapal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKapalActionPerformed(evt);
            }
        });

        buttonPesawat.setBackground(new java.awt.Color(0, 102, 0));
        buttonPesawat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPesawat.setForeground(new java.awt.Color(255, 255, 255));
        buttonPesawat.setText("INPUT KENDARAAN PESAWAT");
        buttonPesawat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesawatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonKapal, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonKeretaApi, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(buttonPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonTruk, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonBus, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonSepeda3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSepeda3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTruk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKeretaApi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(buttonKapal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesawatActionPerformed
        // TODO add your handling code here:
        dispose();
        new FramePesawat().setVisible(true);
    }//GEN-LAST:event_buttonPesawatActionPerformed

    private void buttonSepeda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSepeda3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new FrameSepeda().setVisible(true);
    }//GEN-LAST:event_buttonSepeda3ActionPerformed

    private void buttonMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMotorActionPerformed
        // TODO add your handling code here:
        dispose();
        new FrameMotor().setVisible(true);
    }//GEN-LAST:event_buttonMotorActionPerformed

    private void buttonTrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrukActionPerformed
        // TODO add your handling code here:
        dispose();
        new frameTruckClass().setVisible(true);
    }//GEN-LAST:event_buttonTrukActionPerformed

    private void buttonBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBusActionPerformed
        // TODO add your handling code here:
        dispose();
        new FrameBus().setVisible(true);
    }//GEN-LAST:event_buttonBusActionPerformed

    private void buttonKeretaApiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeretaApiActionPerformed
        // TODO add your handling code here:
        dispose();
        new FrameKeretaApi().setVisible(true);
    }//GEN-LAST:event_buttonKeretaApiActionPerformed

    private void buttonKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKapalActionPerformed
        // TODO add your handling code here:
        dispose();
        new framekapal().setVisible(true);
    }//GEN-LAST:event_buttonKapalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KendaraanMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KendaraanMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KendaraanMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KendaraanMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KendaraanMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBus;
    private javax.swing.JButton buttonKapal;
    private javax.swing.JButton buttonKeretaApi;
    private javax.swing.JButton buttonMotor;
    private javax.swing.JButton buttonPesawat;
    private javax.swing.JButton buttonSepeda3;
    private javax.swing.JButton buttonTruk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
